TicketBundle\Entity\Subscriber:
    type: entity
    table: t_subscriber
    repositoryClass: TicketBundle\Entity\SubscriberRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        first_name:
            type: string
            length: 255

        last_name:
            type: string
            length: 255

        email:
            type: string
            length: 255

        number_of_price1:
            type: integer
            nullable: true

        number_of_price2:
            type: integer
            nullable: true

        commentary:
            type: text
            nullable: true

        payment_state:
            type: string
            length: 255

        total_price:
            type: decimal
            precision: 10
            scale: 2
            nullable: true

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update


    manyToOne:
        ticket:
          targetEntity: TicketBundle\Entity\Ticket
          joinColumn:
            name: ticket_id
            referencedColumnName: id