TicketBundle\Entity\Ticket:
    type: entity
    table: t_ticket
    repositoryClass: TicketBundle\Entity\TicketRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:

        external:
            type: integer

        title:
            type: string
            length: 255

        title_business:
            type: string
            length: 255

        address:
            type: string
            length: 255
            nullable: true

        date_time:
            type: string
            length: 255

        description:
            type: text
            nullable: true


        price_1_title:
            type: string
            length: 255

        price_1:
            type: decimal
            precision: 10
            scale: 2
            message: Geen letters toegestaan.


        price_2_title:
            type: string
            length: 255
            nullable: true

        price_2:
            type: decimal
            precision: 10
            scale: 2
            message: Geen letters toegestaan.
            nullable: true



    oneToMany:
        subscribers:
            targetEntity: Subscriber
            mappedBy: ticket