base:
    resource: "@PageBundle/Resources/config/routing.yml"
    prefix:   /admin

page:
    resource: "@PageBundle/Resources/config/routing.yml"
    prefix:   /admin/page

index:
    resource: "@TicketBundle/Resources/config/routing.yml"
    prefix:   /

