services:
    page.form.type.prefixed_text:
        class: PageBundle\Form\Type\PrefixedTextType
        tags:
            - { name: form.type, alias: prefixed_text }

    page.form.type.suffixed_text:
        class: PageBundle\Form\Type\SuffixedTextType
        tags:
            - { name: form.type, alias: suffixed_text }
