PageBundle\Entity\Block:
    type: entity
    table: block
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:

        module:
            type: array
            nullable: true

        position:
            type: integer


    manyToOne:
        pillar:
          targetEntity: PageBundle\Entity\Pillar
          joinColumn:
            name: pillar_id
            referencedColumnName: id
